CREATE SCHEMA IF NOT EXISTS suppliers;

CREATE TABLE IF NOT EXISTS suppliers.suppliers (
    id BIGSERIAL PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE,
    address VARCHAR(255) NOT NULL,
    contact VARCHAR(50) NOT NULL
    );

