apiVersion: 1

datasources:
  - name: prometheus
    type: prometheus
    uid: prometheus
    orgId: 1
    url: http://prometheus:9090
    basicAuth: false
    isDefault: false
    version: 1
    editable: false
    jsonData:
      httpMethod: GET

  - name: loki
    type: loki
    uid: loki
    orgId: loki
    url: http://loki:3100
    basicAuth: false
    isDefault: false
    version: 1
    editable: false
